job_portal/account/urls.py
from django.urls import path, include
from account import views
from account.views import (JobseekerSignupView, EmployerSignupView, 
                             JobseekerProfileUpdateView, EmoloyerProfileDetailView,
                             JobseekerProfileDetailView)

from jobs.views import (EmployerDashboard)
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('over', views.index, name = 'index'),
    path('account/jobseeker/register', JobseekerSignupView.as_view(), name = 'register-jobseeker'),
    path('account/employer/register', EmployerSignupView.as_view(), name = 'register-employer'),
    path('register-as', views.register_as, name = 'register_as'),

    path('jobseeker/', include(([
        path('profile/detail/<int:user_id>', JobseekerProfileDetailView.as_view(), name = 'jobseeker_profile_detail'),
        path('profile/update/detail', views.JobseekerProfileUpdateView, name = 'jobseeker_profile_add_detail'),
        path('profile/settings', views.JobseekerSetting, name = 'jobseeker_profile_setting'),
        path('profile/change/password', views.JobseekerChangePassword, name = 'jobseeker_change_password'),
    ], 'account.views' ), namespace='jobseeker')),


    path('employer/', include(([
        path('dashboard/<str:username>', EmployerDashboard.as_view(), name = 'employer_dashboard'),
        path('profile/detail/<int:user_id>', EmoloyerProfileDetailView.as_view(), name = 'employer_profile_detail'),
        path('profile/update/detail/', views.EmployerProfileUpdateView, name = 'employer_profile_update_detail'),
        path('profile/settings', views.EmployerSettings, name = 'employer_settings'),
        path('profile/change/password', views.EmployerPasswordChange, name = 'employer_change_password')
    ], 'account.views' ), namespace='employer')),
    
    path('login', auth_views.LoginView.as_view(template_name='register/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='register/logout.html'), name='logout'),
    path('password-reset', auth_views.PasswordResetView.as_view(template_name='register/passwords/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='register/passwords/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='register/passwords/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-reset', auth_views.PasswordResetCompleteView.as_view(template_name='register/passwords/password_reset_complete.html'), name='password_reset_complete'),
    path('delete/account/<int:id>', views.delete_acccount, name='delete_account')

]

job_portal/faq/urls.py
from django.urls import path, include
from faq import views
from faq.views import FaqForJobseekerListView, FaqForJobseekerDetailView, FaqForEmployerListView, FaqForEmployerDetailView

urlpatterns = [
    path('jobseeker/', include(([
        path('faq/list', FaqForJobseekerListView.as_view(), name = 'jobseeker_faq_list'),
        path('faq/detail/<int:pk>',FaqForJobseekerDetailView.as_view(), name = 'jobseeker_faq_detail'),
    ], 'faq.views' ), namespace='jobseeker_faq')),

    path('employer/', include(([
        path('faq/list', FaqForEmployerListView.as_view(), name = 'employer_faq_list'),
        path('faq/detail/<int:pk>',FaqForEmployerDetailView.as_view(), name = 'employer_faq_detail'),
    ], 'faq.views' ), namespace='employer_faq')),
]

job_portal/job_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = 'SmartKTM Jobs'
admin.site.site_title = 'SmartKTM Jobs admin'
admin.site.index_title = 'SmartKTM Jobs administration'
admin.empty_value_display = '**Empty**'

urlpatterns = [
    path('smartktmadmin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('jobs.urls')),
    path('', include('contact.urls')),
    path('', include('blog.urls')),
    path('', include('faq.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


job_portal/jobs/urls.py
from django.urls import path, include
from account import views
from jobs import views as JobsView
from account.views import (JobseekerProfileUpdateView)

from jobs.views import ( JobPostCreateView, MyJobDetailView, JobLists,
                         MyJobUpdateView, MyJobDeleteView, JobApplyCreateView,
                         AppliedJobListView, JobseekerProfileListView,
                         HowItWorks, JobseekerProfileDetailView,
                         EmployerProfileListView, EmployerProfileDetailView,
                         AboutSmartKTM, )
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', JobLists.as_view(), name='homes'),
    path('browse/jobs', JobsView.BrowseJobView, name = 'browse_job'),
    path('job/detail/<int:id>', JobsView.BrowseJobDetail, name='jobs_detail'),
    path('job/save/<int:id>', JobsView.SaveJobs, name='save_jobs'),
    path('saved/jobs', JobsView.ViewSavedJobs, name='saved_jobs'),
    path('job/detail/<int:pk>/apply', JobApplyCreateView.as_view(), name='job_apply'),
    path('applied/jobs/<str:username>', AppliedJobListView.as_view(), name='applied_jobs'),
    path('how/it/works', HowItWorks.as_view(), name='how_works'),
    path('about/smart/ktm/jobs', AboutSmartKTM.as_view(), name='about_us'),
    path('jobseeker/details/<str:username>/<int:pk>', JobseekerProfileDetailView.as_view(), name='jobseeker_detaillls'),
    path('jobseeker/profile/list', JobseekerProfileListView.as_view(), name='jobseeker_profile'),
    path('employer/details/<str:username>/<int:pk>', EmployerProfileDetailView.as_view(), name='employer_detaillls'),
    path('employer/profile/list', EmployerProfileListView.as_view(), name='employer_profile'),



    path('employer/', include(([
        path('job/post', JobPostCreateView.as_view(), name='job_post'),
        # path('my/jobs/<str:username>', MyJobListView.as_view(), name='my_job_list'),
        path('my/jobs/<int:pk>/update', MyJobUpdateView.as_view(), name='my_job_update'),
        path('my/jobs/<int:pk>/delete', MyJobDeleteView.as_view(), name='my_job_delete'),
        path('my/jobs/public/preview/<str:username>/<int:pk>', MyJobDetailView.as_view(), name='my_job_detail'),
        # path('applicant/<int:user_id>/profile', JobsView.ApplicantDetailView, name='applicant_profile_detail')


    ], 'jobs.views'), namespace='jobs_employer')),

    

]

job_portal/jobs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from jobs.forms import job_post_form, JobApplyForm
from account.decorators import jobseeker_required, employer_required
from django.contrib.auth.decorators import login_required
from django.views.generic import View, TemplateView, CreateView, UpdateView, DetailView, DeleteView, ListView
from jobs.models import JobPost, JobApply
from account.models import User, JobseekerProfile, EmployerProfile
from django.core.paginator import Paginator
from django.utils.decorators import method_decorator
from jobs.filers import FilterTime
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib import messages
from jobs.decorators import complete_profile_required, complete_employer_profile



class JobLists(ListView):
    queryset = JobPost.objects.filter(status='Approved')
    template_name = 'account/home.html'
    context_object_name = 'Jobs'
    paginate_by = 20
    ordering = '-JobPostDate'




# For employer's views 


@method_decorator([login_required, employer_required, complete_employer_profile], name='dispatch')
class JobPostCreateView(CreateView):
    model = JobPost
    form_class = job_post_form
    template_name = 'jobs/employer/job_post.html'


    def get_context_data(self, **kwargs):
        kwargs['post_type'] = 'Post'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


@method_decorator([login_required, employer_required], name='dispatch')
class EmployerDashboard(ListView):
    queryset = JobPost.objects.all()
    template_name = 'account/Employer/dashboard.html'
    context_object_name = 'mypost'
    paginate_by = 10

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return JobPost.objects.filter(user=user).order_by('-JobPostDate')






@method_decorator([login_required, employer_required], name='dispatch')
class MyJobDetailView(UserPassesTestMixin, DetailView):
    model = JobPost
    template_name = 'jobs/employer/my_job_detail.html'
    context_object_name = 'mypost'

    def test_func(self):
        jobpost = self.get_object()
        if self.request.user == jobpost.user:
            return True
        return False



 


# Job Updateing Views
@method_decorator([login_required, employer_required], name='dispatch')
class MyJobUpdateView(UserPassesTestMixin, UpdateView):
    model = JobPost
    form_class = job_post_form
    template_name = 'jobs/employer/job_post.html'

    def get_context_data(self, **kwargs):
        kwargs['post_type'] = 'Update'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        jobpost = self.get_object()
        if self.request.user == jobpost.user:
            return True
        return False


# job delete view
@method_decorator([login_required, employer_required], name='dispatch')
class MyJobDeleteView(UserPassesTestMixin, DeleteView):
    model = JobPost
    template_name = 'jobs/employer/my_job_delete.html'


    def get_absolute_url(self):
        return reverse("employer:employer_dashboard", kwargs={'username':self.user.username})


    def test_func(self):
        jobpost = self.get_object()
        if self.request.user == jobpost.user:
            return True
        return False

    

    










def is_valid_queryparm(parm):
    return parm != '' and parm is not None



def BrowseJobView(request):
    jobs = JobPost.objects.filter(status='Approved').order_by('-JobPostDate')
    print(jobs)

    # search jobs
    title = request.GET.get('title')
    if is_valid_queryparm(title):
        jobs = jobs.filter(JobTitle__icontains = title)

    location = request.GET.get('location')
    if is_valid_queryparm(location):
        jobs = jobs.filter(Location__icontains = location)

    yourskill = request.GET.get('yourskill')
    if is_valid_queryparm(yourskill):
        jobs = jobs.filter(RequiredSkill__icontains=yourskill)

    # filter jobs
    filter = FilterTime(request.GET, queryset=jobs)
    jobs = filter.qs

    startsalary = request.GET.get('startsalary')
    if is_valid_queryparm(startsalary):
        jobs = jobs.filter(SalaryStart__icontains=startsalary)

    endsalary = request.GET.get('endsalary')
    if is_valid_queryparm(endsalary):
        jobs = jobs.filter(EndSalary__icontains=endsalary)


    paginator = Paginator(jobs, 30, orphans=5)
    page_number = request.GET.get('page')
    jobs = paginator.get_page(page_number)

    contex = {'Jobs':jobs, 'time':filter}
    return render(request, 'jobs/jobseeker/browse_job.html', contex)


def BrowseJobDetail(request, id):
    jobs = get_object_or_404(JobPost, id=id)
    visitor_ip_address = request.META.get("REMOTE_ADDR")
    jobs.views = jobs.views + 1
    jobs.save()
    is_SaveJob = False
    if request.user.is_authenticated:
        if request.user.is_jobseeker:
            if jobs.SaveJob.filter(id=request.user.jobseekerprofile.user_id).exists():
                is_SaveJob = True
    contex = {'mypost':jobs, 'is_save':is_SaveJob, 'clint_ip': visitor_ip_address}
    return render(request, 'jobs/jobseeker/job_detail.html', contex)


@login_required
@jobseeker_required
def SaveJobs(request, id):
    jobpost = get_object_or_404(JobPost, id=id)
    if jobpost.SaveJob.filter(id=request.user.jobseekerprofile.user_id).exists():
        jobpost.SaveJob.remove(request.user.jobseekerprofile.user_id)
    else:
        jobpost.SaveJob.add(request.user.jobseekerprofile.user_id)
    return redirect('jobs_detail', id) #HttpResponseRedirect(jobpost.get_absolute_url())


@login_required
@jobseeker_required
def ViewSavedJobs(request):
    user = request.user.jobseekerprofile.user_id
    saved_jobs = JobPost.objects.filter(SaveJob=user)
    contex = {'SavedJobs':saved_jobs}
    return render(request, 'jobs/jobseeker/saved_jobs.html', contex)





@method_decorator([login_required, jobseeker_required, complete_profile_required], name='dispatch')
class JobApplyCreateView(CreateView):
    model = JobApply
    form_class = JobApplyForm
    template_name = 'jobs/jobseeker/job_apply.html'
    context_object_name = 'job'
    # fields = '__all__'


    def get_success_url(self):
        return reverse_lazy('jobs_detail', kwargs={'id': self.kwargs['pk']})

    def form_valid(self, form):
        applicant = JobApply.objects.filter(user_id=self.request.user.id, job_id=self.kwargs['pk'])
        if applicant:
            messages.info(self.request, 'You already applied for this job')
            # return redirect('jobs_detail', id=id)
            return HttpResponseRedirect(self.get_success_url())
        form.instance.user = self.request.user
        form.instance.job_id = self.kwargs['pk']
        messages.success(self.request, 'Job has been Applied!')
        print(messages)
        return super().form_valid(form)


@method_decorator([login_required, jobseeker_required], name='dispatch')
class AppliedJobListView(ListView):
    model = JobApply
    template_name = 'jobs/jobseeker/applied_jobs.html'
    context_object_name = 'job'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return JobApply.objects.filter(user = user)
    




# visit jobseeker profile 
@method_decorator([login_required], name='dispatch')
class JobseekerProfileListView(ListView):
    model = JobseekerProfile
    template_name = 'jobs/employer/jobseeker_list.html'
    context_object_name = 'jobseeker'
    
@method_decorator([login_required], name='dispatch')
class JobseekerProfileDetailView(DetailView):
    model = JobseekerProfile
    template_name = 'jobs/employer/jobseeker_detail.html'
    context_object_name = 'profile'


# visit employer profile 
@method_decorator([login_required], name='dispatch')
class EmployerProfileListView(ListView):
    model = EmployerProfile
    template_name = 'jobs/jobseeker/employer_list.html'
    context_object_name = 'employer'


@method_decorator([login_required], name='dispatch')
class EmployerProfileDetailView(DetailView):
    model = EmployerProfile
    template_name = 'jobs/jobseeker/employer_detail.html'
    context_object_name = 'profile'



# How it works template

class HowItWorks(TemplateView):
    template_name = 'how_it_works.html'


class AboutSmartKTM(TemplateView):
    template_name = 'about.html'

job_portal/jobs/templates/jobs/employer/job_post.html
{% extends 'account/Employer/employer_profile.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block profilecontents %}
     <div class="container p-5">
      <div class="row">
          <div class="col-2">
          </div>
            <div class="col-8 shadow-lg p-3 mb-5 bg-white rounded ">
                <div class="container rounded">
                    <form method = 'POST', novalidate>
                    {% csrf_token %}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Job {{ post_type }}</legend>
                            <div class = "container">
                                {{ form.media }}
                                {{ form|crispy }}
                            </div>
                        </fieldset>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-info btn-block">Save and request to admin</button>
                        </div>
                    </form>
                </div>
             </div>                 
          
          <div class="col-2">
          </div>
      </div>
  </div>    
  
{% endblock profilecontents %}

job_portal/jobs/templates/jobs/employer/jobseeker_list.html
{% extends 'account/Employer/employer_profile.html' %}
{% load static %}

{% block profilecontents %}
    <div class="container">
        <div class="row bg-white m-5">
        {% if not jobseeker %}
            Jobseeker are not avaliable yet...
        {% else %}
            {% for jobseeker in jobseeker %}
                <div class="col-4 mt-5 mb-5 ">
                    <a class="p-5" href="{% url 'jobseeker_detaillls' jobseeker.user.username jobseeker.user.id %}">{{ jobseeker.user.jobseekerprofile.FirstName }} {{ jobseeker.user.jobseekerprofile.LastName }}</a>       
                </div>
            {% endfor %}
        {% endif %}
        </div>
    </div>
{% endblock profilecontents %}  

job_portal/jobs/templates/jobs/employer/my_job_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">

    <div class="card mt-5">
        <div class="card-header">
            User Account Delete
        </div>
        <div class="card-body">
            <div class="alert alert-danger" role="alert">
                Are you sure want to pernamantely delete "{{ object.JobTitle }}" Job Posts

            </div>
            <form method="POST">
                {% csrf_token %}
                    <a href="{% url 'jobs_employer:my_job_detail' object.user.username object.id  %}" class="btn btn-outline-info">Cancel</a>
                    <button type="submit" class="btn btn-danger">
                    Yes, Delete
                    </button>
            </form>

        </div>
        
        
    </div>
</div>
{% endblock content %}

job_portal/jobs/templates/jobs/employer/my_job_detail.html
{% extends 'account/Employer/employer_profile.html' %}
{% load static %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}


{% block profilecontents %}



<div class="container">
   <div class="row mt-5">
    <div class="col-md-7">
      <div class="company-banner">
        <img src="{{ mypost.HiringBanner.url }}" class="img-fluid">
      </div>

      <div class="company-profile mt-4 bg-white p-3">
        <div class="row bg-white profile-section no-gutters">
          <div class="col-md-3 mt-3 company-logo">
            <img src="{{ object.user.employerrprofile.CompanyLogo.url }}" class="img-fluid rounded-circle">
          </div>

          <div class="col-md-9 mt-3 company-name">
            <h4> {{ mypost.user.employerrprofile.CompanyName }}</h4>
            <small>{{ mypost.user.employerrprofile.CompanyCategory }}</small><br>
            <h6><i class="fa fa-map-marker"></i> {{ mypost.user.employerrprofile.CompanyAddress }}</h6>

            <a href="{% url 'employer:employer_profile_detail' mypost.user.id %}" target="_blank" class="button-view-company-profile">View company Profile</a>
          </div>
        </div>
      </div>

      <div class=" mt-2 mb-5 job-section">
        <div class="basic-job-information-section border mb-3 bg-white">
        <h5 class="job-info p-3 border">{{ mypost.JobTitle }} <small><i class="fa fa-eye"></i> views({{ mypost.views }})</small></h5>
          <h5 class="job-info p-3 border-bottom">Basic Job Information</h5>

          <div class="container mb-5">
              <table class="table table-hover table-responsive table-borderless border-0">
                <tr>
                  <th scope="row">Job Category:</th>
                  <td>{{ mypost.JobCategory }}</td>
                </tr>
                <tr>
                  <th scope="row"> Location :</th>
                  <td>{{ mypost.Location }}</td>
                </tr>
                <tr>
                  <th scope="row">Number Of Vacancies:</th>
                  <td>{{ mypost.NumberOfVacancies }}</td>
                </tr>
                <tr>
                  <th scope="row">Job Level:</th>
                  <td>{{ mypost.JobLevel }}</td>
                </tr>
                <tr>
                  <th scope="row">Time:</th>
                  <td>{{ mypost.AvaliableTime }}</td>
                </tr>

                <tr>
                  <th scope="row">Salary:</th>
                  <td> {% if mypost.SalaryStart and mypost.EndSalary > 0 %} Rs. {{ mypost.SalaryStart }} - {{ mypost.EndSalary }} Monthly {% else %} Negotiable {% endif %}</td>
                </tr>

                <tr>
                  <th scope="row">Shift:</th>
                  <td> {{ mypost.JobShift }}</td>
                </tr>

                <tr>
                  <th scope="row">Required Education:</th>
                  <td> {{ mypost.RequiredEducation }} year</td>
                </tr>

                <tr>
                  <th scope="row">Required Experience:</th>
                  <td> {{ mypost.RequiredExperience }}</td>
                </tr>
                

                <tr>
                  <th scope="row">Required Skill:</th>
                  <td> {{ mypost.RequiredSkill }}</td>
                </tr>

                <tr>
                  <th scope="row">Gender:</th>
                  <td> {{ mypost.Gender }}</td>
                </tr>


                                            
              </table>
          </div>
        </div>
            

        <div class="job-description border mb-3 bg-white">
          <h3 class="job-info p-3 border-bottom">Job Descriptions</h3>
          <div class="container mb-5">
            {{ mypost.JobDescreptions|safe }}
          </div>
        </div>


        <div class="job-specification border mb-2 bg-white">
          <h3 class="job-info p-3 border-bottom">Job Specification</h3>
          <div class="container mb-5">
            {{ mypost.JobSpecification|safe }}
          </div>
        </div>

        <div class="job-specification border mb-5 bg-white">
          <div class="row">
              
              <div class="col-sm-4">
                <a href="" class="btn disabled" aria-disabled="true"><i class="fa fa-eye"></i>Views({{ mypost.views }})</a>
              </div>
              <div class="col-sm-4 ml-auto">
                <a href="https://www.facebook.com/sharer/sharer.php?u=http://127.0.0.1:8000/job/detail/{{ mypost.id }}" class="btn" target = "_blank"><i class="fa fa-facebook fa-lg"></i></a>
                <a href="https://twitter.com/home?status=http://127.0.0.1:8000/job/detail/{{ mypost.id }}" class="btn" target = "_blank"><i class="fa fa-twitter fa-lg"></i></a>
                <a href="https://www.linkedin.com/shareArticle?mini=true&url=http://127.0.0.1:8000/job/detail/{{ mypost.id }}&title=&summary=&source=" class="btn" target = "_blank"><i class="fa fa-linkedin fa-lg"></i></a>
              </div>
            </div>
        </div>

        

      </div>

    </div>
    <div class="col-md-5">
      <div class="sidebar">
        <div class="container-fluid">
          <div class="job-action border bg-white p-3">
            <h6 class="border-bottom p-0">Job Action</h6>
            <div class="btns d-flex mt-4">
            {% if mypost.user == user %}
                <a href="{% url 'jobs_employer:my_job_delete' mypost.id %}" class="btn button-apply-job"><i class="fa fa-trash"></i> Delete</a>
                <a href="{% url 'jobs_employer:my_job_update' mypost.id %}" class="btn button-save-job"><i class="fa fa-edit"></i> Edit</a>
            {% endif %}
            </div>
            
            <div class="btns d-flex mt-4">
                <a href="" class="btn button-apply-job disabled" aria-disabled="true"><i class="fa fa-plus"></i> Apply Job</a>
                <a href="" class="btn button-save-job disabled" aria-disabled="true"><i class="fa fa-save"></i> Save Job</a>
            </div>
            <div class="btns d-flex mt-4">
            Notes*:<br>
            1.this page for public preview and edit and delete if you want<br>
            2.this job applicants shows in below

            </div>
          </div>
        </div>
      </div>
    </div>

      <div class="job-applied container border mb-5 bg-white">
        <div class = "applicant-section border-bottom">
          <h2 class="article-title ml-5 mt-3">Applicants</h2>
        </div>
          <div class="container pl-5 mt-3 pr-5 mb-3">
                <article class="media-comment content-section mt-1">
                  <div class="media-body">
                    {% if not mypost.jobapplys.all %}
                      No applicants yet..
                      {% else %}
                      {% for applicant in mypost.jobapplys.all %}
                        <div class="article-metadata-username border-bottom">
                          <img class="rounded-circle account-img mb-2" src="{{ applicant.user.jobseekerprofile.ProfileImage.url }}" alt='applied by user'/>
                          <a class="ml-2 " href="{% url 'jobseeker_detaillls' applicant.user.username applicant.user.id %}">{{ applicant.user.jobseekerprofile.FirstName }} {{ applicant.user.jobseekerprofile.LastName }}</a>
                          <a href="{{ applicant.user.jobseekerprofile.UploadCv.url }}" class="btn button-apply-job" target="_blank"><i class="fa fa-download"></i> Download Cv </a>
                          <small class="text-muted ml-2">{{ applicant.ApplydDate|timesince }}</small>            
                        </div>
                        <h3 class="article-title">Why he/she choose this job</h3>
                        <p class="article-content">{{ applicant.JobApplyReason|safe }}</p><hr><br>
                        
                      {% endfor %}
                    {% endif %}  
                  </div>
                </article>
          </div>
  </div>
  </div>
 </div>

{% endblock profilecontents %}

job_portal/jobs/templates/jobs/employer/my_job_list.html
{% extends 'account/Employer/employer_profile.html' %}
{% load static %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}


{% block profilecontents %}
       
{% for i in mypost %}
  <div class="container p-2 mt-3 mb-3">
    <article class="media content-section mt-1 ">
      <img class="rounded-circle account-img p-1" src="{{ i.user.employerrprofile.CompanyLogo.url }}"/>
      <div class="media-body mr-3">
        <div class="article-metadata">
          <a class="mr-2" href="">{{i.user}}</a>
          <small class="text-muted">{{i.JobPostDate|date:"F d, Y"}}</small>
        </div>
        <h2><a class="article-title" href="{% url 'jobs_employer:my_job_detail' i.user.username i.id %}">{{ i.JobTitle|safe }}</a></h2>
        <p class="article-content">{{i.JobDescreptions|safe|slice:":200"}}...</p>
        <div class="media-footer border rounded">
          </div>
        </div>
      </div>
      
    </article>
    
  </div>
 {% endfor %} 
    <!-- paginator -->
    <div class="container mt-3 ml-5 mr-5">
    {% if is_paginated %}
    {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
    {% endif %}
    </div>

{% endblock profilecontents %}