job_portal/account/urls.py
from django.urls import path, include
from account import views
from account.views import (JobseekerSignupView, EmployerSignupView, 
                             JobseekerProfileUpdateView, EmoloyerProfileDetailView,
                             JobseekerProfileDetailView)

from jobs.views import (EmployerDashboard)
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('over', views.index, name = 'index'),
    path('account/jobseeker/register', JobseekerSignupView.as_view(), name = 'register-jobseeker'),
    path('account/employer/register', EmployerSignupView.as_view(), name = 'register-employer'),
    path('register-as', views.register_as, name = 'register_as'),

    path('jobseeker/', include(([
        path('profile/detail/<int:user_id>', JobseekerProfileDetailView.as_view(), name = 'jobseeker_profile_detail'),
        path('profile/update/detail', views.JobseekerProfileUpdateView, name = 'jobseeker_profile_add_detail'),
        path('profile/settings', views.JobseekerSetting, name = 'jobseeker_profile_setting'),
        path('profile/change/password', views.JobseekerChangePassword, name = 'jobseeker_change_password'),
    ], 'account.views' ), namespace='jobseeker')),


    path('employer/', include(([
        path('dashboard/<str:username>', EmployerDashboard.as_view(), name = 'employer_dashboard'),
        path('profile/detail/<int:user_id>', EmoloyerProfileDetailView.as_view(), name = 'employer_profile_detail'),
        path('profile/update/detail/', views.EmployerProfileUpdateView, name = 'employer_profile_update_detail'),
        path('profile/settings', views.EmployerSettings, name = 'employer_settings'),
        path('profile/change/password', views.EmployerPasswordChange, name = 'employer_change_password')
    ], 'account.views' ), namespace='employer')),
    
    path('login', auth_views.LoginView.as_view(template_name='register/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='register/logout.html'), name='logout'),
    path('password-reset', auth_views.PasswordResetView.as_view(template_name='register/passwords/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='register/passwords/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='register/passwords/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-reset', auth_views.PasswordResetCompleteView.as_view(template_name='register/passwords/password_reset_complete.html'), name='password_reset_complete'),
    path('delete/account/<int:id>', views.delete_acccount, name='delete_account')

]

job_portal/faq/urls.py
from django.urls import path, include
from faq import views
from faq.views import FaqForJobseekerListView, FaqForJobseekerDetailView, FaqForEmployerListView, FaqForEmployerDetailView

urlpatterns = [
    path('jobseeker/', include(([
        path('faq/list', FaqForJobseekerListView.as_view(), name = 'jobseeker_faq_list'),
        path('faq/detail/<int:pk>',FaqForJobseekerDetailView.as_view(), name = 'jobseeker_faq_detail'),
    ], 'faq.views' ), namespace='jobseeker_faq')),

    path('employer/', include(([
        path('faq/list', FaqForEmployerListView.as_view(), name = 'employer_faq_list'),
        path('faq/detail/<int:pk>',FaqForEmployerDetailView.as_view(), name = 'employer_faq_detail'),
    ], 'faq.views' ), namespace='employer_faq')),
]

job_portal/job_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = 'SmartKTM Jobs'
admin.site.site_title = 'SmartKTM Jobs admin'
admin.site.index_title = 'SmartKTM Jobs administration'
admin.empty_value_display = '**Empty**'

urlpatterns = [
    path('smartktmadmin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('jobs.urls')),
    path('', include('contact.urls')),
    path('', include('blog.urls')),
    path('', include('faq.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


job_portal/jobs/urls.py
from django.urls import path, include
from account import views
from jobs import views as JobsView
from account.views import (JobseekerProfileUpdateView)

from jobs.views import ( JobPostCreateView, MyJobDetailView, JobLists,
                         MyJobUpdateView, MyJobDeleteView, JobApplyCreateView,
                         AppliedJobListView, JobseekerProfileListView,
                         HowItWorks, JobseekerProfileDetailView,
                         EmployerProfileListView, EmployerProfileDetailView,
                         AboutSmartKTM, )
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', JobLists.as_view(), name='homes'),
    path('browse/jobs', JobsView.BrowseJobView, name = 'browse_job'),
    path('job/detail/<int:id>', JobsView.BrowseJobDetail, name='jobs_detail'),
    path('job/save/<int:id>', JobsView.SaveJobs, name='save_jobs'),
    path('saved/jobs', JobsView.ViewSavedJobs, name='saved_jobs'),
    path('job/detail/<int:pk>/apply', JobApplyCreateView.as_view(), name='job_apply'),
    path('applied/jobs/<str:username>', AppliedJobListView.as_view(), name='applied_jobs'),
    path('how/it/works', HowItWorks.as_view(), name='how_works'),
    path('about/smart/ktm/jobs', AboutSmartKTM.as_view(), name='about_us'),
    path('jobseeker/details/<str:username>/<int:pk>', JobseekerProfileDetailView.as_view(), name='jobseeker_detaillls'),
    path('jobseeker/profile/list', JobseekerProfileListView.as_view(), name='jobseeker_profile'),
    path('employer/details/<str:username>/<int:pk>', EmployerProfileDetailView.as_view(), name='employer_detaillls'),
    path('employer/profile/list', EmployerProfileListView.as_view(), name='employer_profile'),



    path('employer/', include(([
        path('job/post', JobPostCreateView.as_view(), name='job_post'),
        # path('my/jobs/<str:username>', MyJobListView.as_view(), name='my_job_list'),
        path('my/jobs/<int:pk>/update', MyJobUpdateView.as_view(), name='my_job_update'),
        path('my/jobs/<int:pk>/delete', MyJobDeleteView.as_view(), name='my_job_delete'),
        path('my/jobs/public/preview/<str:username>/<int:pk>', MyJobDetailView.as_view(), name='my_job_detail'),
        # path('applicant/<int:user_id>/profile', JobsView.ApplicantDetailView, name='applicant_profile_detail')


    ], 'jobs.views'), namespace='jobs_employer')),

    

]

job_portal/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class = "about_content mb-5" >
    <div class="sec">
  <div class="abt">
    <img src="about.png" alt="SmartKTM">
    
  </div>
  
  <div class="para">
    <h1>SmartKTM jobs</h1> 
  <p>SmartKTM jobs is one of the leading and growing job portals in Kathmandu, Nepal. Our mission is to lead the Internet employment industry in Nepal by providing innovative information, superior resume management software and a comprehensive selection of services.SmartKTM jobs is covering almost every job in Nepalese job market with free job posting service to job provider. RamroJob aims at providing detailed information to job seeker at free of cost. Currently, SmartKTM jobs member are continuously working on website improvement and making website more user-friendly. We, at SmartKTM jobs always respect our customers and job seekers privacy. We don’t sell information about our clients /customer to third party at any cost without their consent.Smart KTM jobs offers services to the recruiting and job-seeking community in Kathmandu, Nepal. We are the only recruitment service provider with 100% free service to all the jobseekers.
  It is our mission to bring the burgeoning Nepalese Internet and computing talent to bear on international Web development.<br/><br/>
  Jai Nepal!</p>

  
  </div>
</div>

<div class="team">

   <h1 >Our Team</h1>
   <p>Brought together with a vision to design the future of work with proven combination of industry, technology and consulting expertise.</p>
   <div class="member" style="background-color:white;">
    <h3> Ajaya Pudasaini</h3>
    <h2>Co-Founder and Chairman</h2>
    <p>A renowned entrepreneurial leader and specialist with 20+ years’ success in strategic acquisitions.</p>
  </div>
  <div class="member" style="background-color:white;">
    <h3>Dejina Ghale</h3>
    <h2>Co-Founder and Chief Visionary Officer</h2>
    <p>Recruitment and tech thought-leaderwith tremendous industry experience.Former MD of Compuvac and CEO(Europe).

</p>
  </div>
  <div class="member" style="background-color:white;">
    <h3> Hardik Gurung</h3>
    <h2>Chief Operations Officer</h2>
    <p>Former Managing Director of Dice Energy International and Managing Director OilCareers.com.</p>
  </div>
  <div class="member" style="background-color:white;">
    <h3>Sadiksha Pandey</h3>
    <h2>Chief Technical Officer</h2>
    <p>Former Head of R&D and overall head of search for Jobsite. Creator and co-inventor of MyJobMatcher resume search and match engine.</p>
  </div>

  <div class="member" style="background-color:white;">
    <h3> Prasis Gautam</h3>
    <h2>Chief Revenue Officer</h2>
    <p>Former Vice President of Monster - Talent Fusion with over fifteen years of recruitment industry experience.</p>
  </div>
  <div class="member" style="background-color:white;">
    <h3>Sriyanka Prajapati</h3>
    <h2>Advisor</h2>
    <p>A leader specialist in recruitment technology for more than 25 years.co-inventor of MyJobMatcher resume search and match engine.

</p>
  </div>
  <div class="member" style="background-color:white;">
    <h3> Manikant Yadav</h3>
    <h2>Global Creative Director(Supporting Team)</h2>
   
  </div>
  <div class="member" style="background-color:white;">
    <h3>Shantosh Yadav </h3>
    <h2>Head of Marketing (Supporting Team)</h2>
    
  </div>
</div>
</main>
{% endblock content %}

job_portal/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
  
  <!-- custom CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'customcss/style.css' %}">

   <!-- font awesome -->

   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">

  <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
  <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v8.0" nonce="O1jt5YQz"></script>

  <title>Job Finding Application</title>

</head>
<body>

{% block header %}
     <header class="site-header">
      <nav class="navbar navbar-expand-lg">
        <div class="container">


        {% if user.is_authenticated %}
          {% if user.is_jobseeker %}
            <a class="navbar-brand mr-4" href="{% url 'homes' %}">SMARTKTM Jobs</a>
          {% else %}
            <a class="navbar-brand mr-4" href="{% url 'employer:employer_dashboard' user.username %}">SMARTKTM Jobs</a>
          {% endif %}
        {% else %}
        <a class="navbar-brand mr-4" href="{% url 'homes' %}">SMARTKTM Jobs</a>
        {% endif %}
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars"></i>
          <!-- <span class="navbar-toggler-icon "></span>Menu -->
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            
              {% if user.is_authenticated %}
                {% if user.is_jobseeker %}
                  <div class="navbar-nav mr-auto">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'how_works' %}">How It Works </a>
                    </li>
                    <li class="nav-item pl-3">
                      <a class="nav-link" href="{% url 'browse_job' %}">Browse Job</a>
                    </li>
                  </div>
                    <div class="navbar-nav">
                      <li class="nav-item pl-3">
                       <a class="nav-link" href="{% url 'jobseeker:jobseeker_profile_detail' user.id %}">{{ user.username }}</a>
                      </li>
                      <li class="nav-item pl-3">
                       <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                      </li>
                    </div>

                {% else %}
                    <div class="navbar-nav ml-auto">
                      <li class="nav-item dropdown float-right">
                        <a class="nav-link" href="{% url 'employer:employer_dashboard' user.username %}">{{ user.username }}</a>
                      </li>
                      <li class="nav-item dropdown float-right">
                        <a class="nav-link" href=" {% url 'logout' %} ">Logout</a>
                      </li>
                      <a href="{% url 'jobs_employer:job_post' %}" class="btn btn-post-job">Post a Job</a>
                    </div>
                {% endif %}
              {% else %}              
                <div class="navbar-nav mr-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'how_works' %}">How It Works </a>
                  </li>
                  <li class="nav-item pl-3">
                    <a class="nav-link" href="{% url 'browse_job' %}">Browse Job</a>
                  </li>
                </div>
                <!-- Navbar Right Side-->
                <div class="navbar-nav">
                  <li class="nav-item dropdown float-right">
                    <a class="nav-link" href=" {% url 'login' %} ">Login</a>
                  </li>


                  <li class="nav-item dropdown pr-3 pl-3">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Register
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'register-employer' %}">Employeer</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href=" {% url 'register-jobseeker' %} ">Job Seeker</a>
                    </div>
                  </li>
                  <a href="{% url 'jobs_employer:job_post' %}" class="btn btn-post-job">Post a Job</a>
                </div>
              {% endif %}

          </div>
        </div>
      </nav>
    </header>

{% endblock header %}


        

          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
{% block content %}
          
  

{% endblock content %}






<footer id="footer">
  <div class="container-fluid">
    <div class="row ml-5">
      <div class="col-sm-3 mb-5">
        <h4 class="mt-5">About Us In Short</h4>
        <hr color="White">
        <div class="About-Us-In-Short">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          {% comment %} <ul>
            <li><a href="{% url 'about' %}">About US</a></li>
            <li><a href="{% url 'contact' %}">Contact Us</a></li>
            <li><a href="#">Blog</a></li>
          </ul>  {% endcomment %}
        </div>
      </div>
      <div class="col-sm-3">
        <h4 class="mt-5">For JobSeeker</h4>
        <hr color="White">
        <div class="legal">
          <ul>
            <li><a href="{% url 'register-jobseeker' %}">Register</a></li>
            {% if user.is_authenticated %}
            {% if user.is_jobseeker %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
            <li><a href="{% url 'browse_job' %}">Search Jobs</a></li>
            <li><a href="{% url 'jobseeker_faq:jobseeker_faq_list' %}">FAQ</a></li>

          </ul>
        </div>
      </div>
      <div class="col-sm-3">
        <h4 class="mt-5">For Employeers</h4>
        <hr color="White">
        <div class="usefullinks">
          <ul>
            <li><a href="{% url 'register-employer' %}">Register</a></li>
            {% if user.is_authenticated %}
            {% if user.is_employer %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}

            <li><a href="{% url 'jobs_employer:job_post' %}">Post Job</a></li>
            <li><a href="{% url 'employer_faq:employer_faq_list' %}">FAQ</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-3">
        <h4 class="mt-5">Follow Us</h4>
        <hr color="White">
        <div class="socialicon">
          <ul>
            <li><a href="facebook.com"><i class="fa fa-facebook-f"></i></a></li>
            <li><a href="twitter.com"><i class="fa fa-twitter"></i></a></li>
            <li><a href="instagram.com"><i class="fa fa-instagram"></i></a></li>
            <li><a href="youtube.com"><i class="fa fa-youtube"></i></a></li>
            <li><a href="pinterest.com"><i class="fa fa-pinterest-p"></i></a></li>
          </ul>
        </div>
      </div>
      </div>
    </div>
  </div>
</footer>
<nav class="navbar navbar-expand-lg footer-navbar">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fa fa-bars"></i>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="navbar-nav mx-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link linkcol" href="{% url 'blog-list' %}">Blog |</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link linkcol" href="{% url 'contact' %}">Contact Us |</a>
      </li>
       <li class="nav-item">
        <a class="nav-link linkcol" href="{% url 'about_us' %}">About Us |</a>
      </li>
      <li class="nav-item linkcol">
        <a class="nav-link linkcol" href="#">Terms & condition |</a>
      </li>
      <li class="nav-item linkcol">
        <a class="nav-link linkcol" href="#">Privacy Policy</a>
      </li>
    </ul>
  </div>
</nav>

<section class="copyright"><p>Copyright <script type="text/javascript">
  document.write(new Date().getFullYear());
  </script> -Designed and developed by <i class="fa fa-heart"></i> Ajay Pudasaini</p>
</section>

<!-- bootatrap javascript -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

job_portal/templates/how_it_works.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<main class="about_content">
    <div class="pics">
      <img src="{% static 'Image/bg1.jpg' %}" class="d-block w-100 img-fluid" alt="...">
      <div class="tops">
        <h1 >We take care of everything <br> - that's a bonus</h1>
        <p>We have combined artificial intelligence with the blockchain to bring the best jobseekers and great companies together,  led by a team of experienced and innovative recruitment professionals.</p>
    
    </div>
    </div>
    

<section class="sectionsss">
  <nav>
    <img src="{% static 'Image/job.png' %}" alt="jon search picture">
    
  </nav>
  
  <article>
    <h1>SmartKTM jobs is evolving the traditional recruitment model using  technology, enhanced job posting, job finding and feedback </h1> <br/>
<p>This powerful utilization of technology will fulfill our mission to realign the industry away from costly middlemen towards a decentralized, technology-based community for the jobseeker and job provider of the kathmandu.</p>
 <a href="{% url 'jobs_employer:job_post' %}" class="btn btn-post-job">Post a Job</a>
  
  </article>
</section>

<div class="rows p-0">

   <h1 class="mt-2 mb-3">Our recruiting platform allows you to attract <br/>and hire the top talent, assisting you every<br/> step of the way.</h1>
   <div class="columns" style="background-color:white;">

    <h2>Expertise</h2>
    <p>

Our platform has been built to optimize the hiring process for both candidate and employer, led by a team of experienced and innovative recruitment professionals.</p>
  </div>
  <div class="columns" style="background-color:white;">
    <h2>Efficiency</h2>
    <p>Our leading technology works to screen and present employers with the most relevant candidate applications while keeping active job seekers alert to new top jobs.</p>
  </div>
  <div class="columns" style="background-color:white;">
    <h2>Trust</h2>
    <p>We believe that transparency between candidate and employer makes for successful recruitment, therefore our platform encourages relevant information to be displayed within our secure cloud-based system.</p>

  </div>

   <div class="columns" style="background-color:white;">
    <h2>Outreach</h2>
    <p>We utilize all the top channels for quality hires to ensure your jobs attract the right candidates.</p>
  </div>
  <div class="columns" style="background-color:white;">
    <h2>Feeadback</h2>
    <p>Our internal messaging system solves the breakdown in communication between candidates and employers and creates a channel for direct feedback.</p>
  </div>
  <div class="columns" style="background-color:white;">
    <h2>Fraud detect</h2>
    <p>We have a group of experties who constantly monitors the new member registration , new job vacancy post etc. We immediately delete the user or the jobpost if found fake</p>
    
  </div>
</div>
</main>

{% endblock content %}