job_portal/faq/urls.py
from django.urls import path, include
from faq import views
from faq.views import FaqForJobseekerListView, FaqForJobseekerDetailView, FaqForEmployerListView, FaqForEmployerDetailView

urlpatterns = [
    path('jobseeker/', include(([
        path('faq/list', FaqForJobseekerListView.as_view(), name = 'jobseeker_faq_list'),
        path('faq/detail/<int:pk>',FaqForJobseekerDetailView.as_view(), name = 'jobseeker_faq_detail'),
    ], 'faq.views' ), namespace='jobseeker_faq')),

    path('employer/', include(([
        path('faq/list', FaqForEmployerListView.as_view(), name = 'employer_faq_list'),
        path('faq/detail/<int:pk>',FaqForEmployerDetailView.as_view(), name = 'employer_faq_detail'),
    ], 'faq.views' ), namespace='employer_faq')),
]

job_portal/job_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = 'SmartKTM Jobs'
admin.site.site_title = 'SmartKTM Jobs admin'
admin.site.index_title = 'SmartKTM Jobs administration'
admin.empty_value_display = '**Empty**'

urlpatterns = [
    path('smartktmadmin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('jobs.urls')),
    path('', include('contact.urls')),
    path('', include('blog.urls')),
    path('', include('faq.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


job_portal/faq/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone

For_FAQ_Choose=(
    (0, "Draft"),
   (1, "Jobseeker"),
   (2, "Employer")
)


class Faqs(models.Model):
    question = models.CharField(max_length=1000, verbose_name='Question')
    answer = RichTextField(verbose_name='Answer')
    for_who = models.IntegerField(choices=For_FAQ_Choose, verbose_name='Faq For', default=0)
    created_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.question
    

job_portal/faq/views.py
from django.shortcuts import render, redirect
from faq.models import Faqs
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator


class FaqForJobseekerListView(ListView):
    queryset = Faqs.objects.filter(for_who=1).order_by('-created_on')
    template_name = 'faq/jobseeker/faq_list.html'
    context_object_name = 'faqs'
    paginate_by = 30




class FaqForJobseekerDetailView(DetailView):
    model = Faqs
    template_name = 'faq/jobseeker/faq_detail.html'
    context_object_name = 'faq'




class FaqForEmployerListView(ListView):
    queryset = Faqs.objects.filter(for_who=2).order_by('-created_on')
    template_name = 'faq/employer/faq_list.html'
    context_object_name = 'faq'
    paginate_by = 30


class FaqForEmployerDetailView(DetailView):
    model = Faqs
    template_name = 'faq/employer/faq_detail.html'
    context_object_name = 'faq'

job_portal/faq/templates/faq/jobseeker/faq_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row bg-white m-5 p-5">
            <strong>Question: {{ faq.question }}</strong><br>
            <p>{{ faq.answer|safe }} </p>
        </div>
    </div>
{% endblock content %}

job_portal/faq/templates/faq/jobseeker/faq_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row bg-white m-5">
        {% if not faqs %}
        Faq is not avaliable yet...
        {% else %}
            {% for faq in faqs %}
                <div class="col-6 p-5">
                    <li><a href="{% url 'jobseeker_faq:jobseeker_faq_detail' faq.id %}">{{ faq.question }}</a></li>
                </div>
            {% endfor %}
        {% endif %}
        </div>
    </div>
{% endblock content %}